version: '2.1'

services:

  # ------------------------------------------------------------------------------

  teleproxy:
    command:
      --group ${GROUP} --token ${TOKEN} --db_connect ${DSN} --template ${TEMPLATE}
    networks:
      - web
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./../../teleproxy-data:/data
    build:
      context: .

# uncomment networks to use db container

networks:
  web:
    external:
      name: ${DCAPE_NET}
